spring.application.name=timesheet-service
server.port=8583

spring.config.import=configserver:http://localhost:8590

logging.level.org.springframework.security: DEBUG

# Kafka Configuration
spring.kafka.bootstrap-servers=kafka:29092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer