--liquibase formatted sql

--changeset shoham-kar:init
CREATE TABLE timesheet (
    -- Fields from BaseEntity
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                           created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                           modified_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                           created_by BIGINT NOT NULL,
                           modified_by BIGINT NOT NULL,
                           active BOOLEAN DEFAULT TRUE NOT NULL,

    -- Fields from Timesheet
                           customer_id BIGINT NOT NULL,
                           employee_id BIGINT NOT NULL,
                           project_id BIGINT NOT NULL,
                           task_id BIGINT,
                           cost_code_id BIGINT,
                           seconds BIGINT NOT NULL, -- Storing Duration as nanoseconds or seconds
                           date_worked DATE NOT NULL,
                           start_time TIME WITHOUT TIME ZONE NOT NULL,

                           CONSTRAINT pk_timesheet PRIMARY KEY (id)
);

CREATE INDEX idx_timesheet_customer_employee ON timesheet(customer_id, employee_id);
CREATE INDEX idx_timesheet_date_worked ON timesheet(date_worked);