--liquibase formatted sql

--changeset shoham-kar:init-earnings
CREATE TABLE earning (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    modified_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_by BIGINT NOT NULL,
    modified_by BIGINT NOT NULL,
    active BOOLEAN DEFAULT TRUE NOT NULL,

    timesheet_id BIGINT NOT NULL,
    employee_id BIGINT NOT NULL,
    customer_id BIGINT NOT NULL,
    pay_rate NUMERIC(19, 2) NOT NULL,
    hours_worked NUMERIC(19, 2) NOT NULL,
    gross_amount NUMERIC(19, 2) NOT NULL,
    status VARCHAR(20) NOT NULL,

    CONSTRAINT pk_earning PRIMARY KEY (id),
    CONSTRAINT uk_earning_timesheet_id UNIQUE (timesheet_id)
);

CREATE INDEX idx_earning_customer_id ON earning(customer_id);
CREATE INDEX idx_earning_employee_id ON earning(employee_id);
CREATE INDEX idx_earning_customer_employee ON earning(customer_id, employee_id);
