spring.application.name=payroll-service
server.port=8584

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5534/cf_payroll_db
spring.datasource.username=myuser
spring.datasource.password=mypass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# Liquibase Configuration
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/changelog.xml

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=payroll-service-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.admin.properties.bootstrap.servers=localhost:9092

# Service Discovery & Config Server
spring.config.import=configserver:http://localhost:8590

# Logging
logging.level.root=INFO
logging.level.com.constructflow.payroll_service=DEBUG
